import 'service.dart';

/// Represents a booked appointment for a specific [Service].
///
/// SQLite mapping notes (Lab 8 concepts):
///   - [id] is nullable; generated by SQLite AUTOINCREMENT on insert.
///   - [appointmentDate] is stored as TEXT in "YYYY-MM-DD" format.
///   - [appointmentTime] is stored as TEXT in "HH:MM" format.
///   - [createdAt] is a Dart [DateTime] stored as ISO-8601 TEXT.
///   - [serviceId] is a foreign key referencing services(id).
///   - [status] values: 'pending', 'confirmed', 'completed', 'cancelled'.
class Appointment {
  final int? id;
  final int serviceId;
  final String customerName;

  /// Date in "YYYY-MM-DD" format (e.g. "2026-09-25").
  final String appointmentDate;

  /// Time in "HH:MM" format (e.g. "10:30").
  final String appointmentTime;

  /// Appointment status: 'pending', 'confirmed', 'completed', 'cancelled'.
  final String status;

  /// Record creation timestamp stored as ISO-8601 TEXT in SQLite.
  final DateTime createdAt;

  /// Parent record optionally included by the server for cache synchronization.
  final Service? service;

  const Appointment({
    this.id,
    required this.serviceId,
    required this.customerName,
    required this.appointmentDate,
    required this.appointmentTime,
    required this.status,
    required this.createdAt,
    this.service,
  });

  // ── SQLite serialization ────────────────────────────────────────────────────

  /// Converts this [Appointment] to a [Map] suitable for sqflite insert/update.
  ///
  /// Pass [includeId] = false when inserting a new row so SQLite generates
  /// the primary key via AUTOINCREMENT.
  Map<String, dynamic> toMap({bool includeId = true}) {
    return {
      if (includeId && id != null) 'id': id,
      'service_id': serviceId,
      'customer_name': customerName,
      'appointment_date': appointmentDate,
      'appointment_time': appointmentTime,
      'status': status,
      // DateTime → ISO-8601 TEXT
      'created_at': createdAt.toIso8601String(),
    };
  }

  factory Appointment.fromMap(Map<String, dynamic> map) {
    return Appointment(
      id: map['id'] as int?,
      serviceId: map['service_id'] as int,
      customerName: map['customer_name'] as String,
      appointmentDate: map['appointment_date'] as String,
      appointmentTime: map['appointment_time'] as String,
      status: map['status'] as String,
      // ISO-8601 TEXT → DateTime
      createdAt: DateTime.parse(map['created_at'] as String),
    );
  }

  // ── JSON serialization (API) ────────────────────────────────────────────────

  /// Converts this [Appointment] to a [Map] matching the backend API's camelCase expectations.
  Map<String, dynamic> toJson() {
    return {
      'serviceId': serviceId,
      'customerName': customerName,
      'appointmentDate': appointmentDate,
      'appointmentTime': appointmentTime,
      // id, status, createdAt are typically generated/managed by backend
    };
  }

  /// Creates an [Appointment] from a camelCase JSON object returned by the API.
  factory Appointment.fromJson(Map<String, dynamic> json) {
    return Appointment(
      id: json['id'] as int?,
      serviceId: json['serviceId'] as int,
      customerName: json['customerName'] as String,
      appointmentDate: json['appointmentDate'] as String,
      appointmentTime: json['appointmentTime'] as String,
      status: json['status'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      service: json['service'] is Map<String, dynamic>
          ? Service.fromJson(json['service'] as Map<String, dynamic>)
          : null,
    );
  }

  // ── Utility ─────────────────────────────────────────────────────────────────

  Appointment copyWith({
    int? id,
    int? serviceId,
    String? customerName,
    String? appointmentDate,
    String? appointmentTime,
    String? status,
    DateTime? createdAt,
  }) {
    return Appointment(
      id: id ?? this.id,
      serviceId: serviceId ?? this.serviceId,
      customerName: customerName ?? this.customerName,
      appointmentDate: appointmentDate ?? this.appointmentDate,
      appointmentTime: appointmentTime ?? this.appointmentTime,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  String toString() =>
      'Appointment(id: $id, serviceId: $serviceId, customerName: $customerName, '
      'date: $appointmentDate, time: $appointmentTime, status: $status)';
}
