import 'service.dart';

/// Represents a digital queue token issued to a user for a specific [Service].
///
/// SQLite mapping notes (Lab 8 concepts):
///   - [id] is nullable; generated by SQLite AUTOINCREMENT on insert.
///   - [createdAt] is a Dart [DateTime] stored as ISO-8601 TEXT in SQLite
///     (SQLite has no native DATETIME type). Parsing uses [DateTime.parse].
///   - [isActive] is stored as INTEGER 1/0 (same bool-to-INTEGER pattern
///     demonstrated in the Service model and Lab 8).
///   - [serviceId] is a foreign key referencing services(id).
class QueueToken {
  final int? id;
  final int serviceId;
  final int tokenNumber;

  /// Queue status values: 'waiting', 'serving', 'completed', 'cancelled'.
  final String status;

  /// Stored in SQLite as ISO-8601 TEXT (e.g. "2026-09-22T10:30:00.000").
  final DateTime createdAt;

  /// Estimated wait time in minutes.
  final int estimatedWaitTime;

  /// Stored in SQLite as INTEGER: 1 = active, 0 = inactive.
  final bool isActive;

  /// Parent record optionally included by the server for cache synchronization.
  final Service? service;

  /// Dynamic queue intelligence
  final int? peopleAhead;
  final int? currentTokenNumber;

  const QueueToken({
    this.id,
    required this.serviceId,
    required this.tokenNumber,
    required this.status,
    required this.createdAt,
    this.estimatedWaitTime = 0,
    this.isActive = true,
    this.service,
    this.peopleAhead,
    this.currentTokenNumber,
  });

  // ── SQLite serialization ────────────────────────────────────────────────────

  /// Converts this [QueueToken] to a [Map] suitable for sqflite insert/update.
  ///
  /// Pass [includeId] = false when inserting a new row so SQLite generates
  /// the primary key via AUTOINCREMENT.
  Map<String, dynamic> toMap({bool includeId = true}) {
    return {
      if (includeId && id != null) 'id': id,
      'service_id': serviceId,
      'token_number': tokenNumber,
      'status': status,
      // DateTime → ISO-8601 TEXT for SQLite storage
      'created_at': createdAt.toIso8601String(),
      'estimated_wait_time': estimatedWaitTime,
      // bool → INTEGER
      'is_active': isActive ? 1 : 0,
      'people_ahead': peopleAhead,
      'current_token_number': currentTokenNumber,
    };
  }

  /// Creates a [QueueToken] from a raw SQLite row map.
  factory QueueToken.fromMap(Map<String, dynamic> map) {
    return QueueToken(
      id: map['id'] as int?,
      serviceId: map['service_id'] as int,
      tokenNumber: map['token_number'] as int,
      status: map['status'] as String,
      // ISO-8601 TEXT → DateTime
      createdAt: DateTime.parse(map['created_at'] as String),
      estimatedWaitTime: map['estimated_wait_time'] as int,
      // INTEGER → bool
      isActive: (map['is_active'] as int) == 1,
      peopleAhead: map['people_ahead'] as int?,
      currentTokenNumber: map['current_token_number'] as int?,
    );
  }

  // ── JSON serialization (API) ────────────────────────────────────────────────

  /// Creates a [QueueToken] from a JSON map (camelCase) returned by the API.
  factory QueueToken.fromJson(Map<String, dynamic> json) {
    return QueueToken(
      id: json['id'] as int?,
      serviceId: json['serviceId'] as int,
      tokenNumber: json['tokenNumber'] as int,
      status: json['status'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      estimatedWaitTime: json['estimatedWaitTime'] as int,
      isActive: json['isActive'] as bool,
      peopleAhead: json['peopleAhead'] as int?,
      currentTokenNumber: json['currentTokenNumber'] as int?,
      service: json['service'] is Map<String, dynamic>
          ? Service.fromJson(json['service'] as Map<String, dynamic>)
          : null,
    );
  }

  /// Converts this [QueueToken] to a JSON map (camelCase) for the API.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'serviceId': serviceId,
      'tokenNumber': tokenNumber,
      'status': status,
      'createdAt': createdAt.toIso8601String(),
      'estimatedWaitTime': estimatedWaitTime,
      'isActive': isActive,
      'peopleAhead': peopleAhead,
      'currentTokenNumber': currentTokenNumber,
    };
  }

  // ── Utility ─────────────────────────────────────────────────────────────────

  QueueToken copyWith({
    int? id,
    int? serviceId,
    int? tokenNumber,
    String? status,
    DateTime? createdAt,
    int? estimatedWaitTime,
    bool? isActive,
    int? peopleAhead,
    int? currentTokenNumber,
  }) {
    return QueueToken(
      id: id ?? this.id,
      serviceId: serviceId ?? this.serviceId,
      tokenNumber: tokenNumber ?? this.tokenNumber,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      estimatedWaitTime: estimatedWaitTime ?? this.estimatedWaitTime,
      isActive: isActive ?? this.isActive,
      peopleAhead: peopleAhead ?? this.peopleAhead,
      currentTokenNumber: currentTokenNumber ?? this.currentTokenNumber,
    );
  }

  @override
  String toString() =>
      'QueueToken(id: $id, serviceId: $serviceId, tokenNumber: $tokenNumber, '
      'status: $status, isActive: $isActive)';
}
